In [1]:
import os
from PIL import Image
import numpy as np


# Set the directory you want to start from
rootDir = 'photos'
for dirName, subdirList, fileList in os.walk(rootDir):
    print('Found directory: %s' % dirName)
    for fname in fileList:
        print('\t%s' % fname)
    

Found directory: photos
	1.jpg
	2.jpg
	3.jpg
	4.jpg
	5.jpg


In [2]:
main_list = []
im = Image.open(dirName+"\\"+fileList[0])
print("----------X------------X-----------------------X\n\n")
im.show()
original_array = np.array(im)
print(original_array.shape)
print(original_array.size)
print(original_array)
print("\n\n----------X------------X-----------------------X\n\n")
new_image = im.resize((200, 200))
resized_array = np.array(new_image)
print(resized_array.size)
print(resized_array.shape)
print(resized_array)
main_list.append(resized_array)

----------X------------X-----------------------X


(2160, 3840, 3)
24883200
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 ...

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


----------X------------X-----------------------X


120000
(200, 200, 3)
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 ...

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


In [3]:
main_list

[array([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        ...,
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=uint8)]

In [4]:
pic = 2
for i in range(1,len(fileList)):
    print("PIC NO : ",pic)
    im = Image.open(dirName+"\\"+fileList[i])           
    print("----------X------------X-----------------------X\n\n")
    im.show()
    original_array = np.array(im)
    print(original_array.shape)
    print(original_array.size)
    print(original_array)
    print("\n\n----------X------------X-----------------------X\n\n")
    new_image = im.resize((200, 200))
    resized_array = np.array(new_image)
    print(resized_array.size)
    print(resized_array.shape)
    print(resized_array)
    print("APPENDING TIME")
    main_list.append(resized_array)
    pic = pic+1

PIC NO :  2
----------X------------X-----------------------X


(1200, 1600, 3)
5760000
[[[234 183 180]
  [227 171 172]
  [233 172 177]
  ...
  [171  13  14]
  [166   8   9]
  [168  10  11]]

 [[228 172 173]
  [235 176 178]
  [248 186 191]
  ...
  [162   4   5]
  [166   8   9]
  [170  12  13]]

 [[244 182 185]
  [255 191 195]
  [255 192 196]
  ...
  [173  15  16]
  [186  28  29]
  [181  23  24]]

 ...

 [[119 196 206]
  [115 192 202]
  [117 194 204]
  ...
  [  3 132 161]
  [  4 133 164]
  [  5 134 165]]

 [[124 201 211]
  [120 197 207]
  [120 197 207]
  ...
  [  1 130 159]
  [  3 132 163]
  [  5 134 165]]

 [[123 200 210]
  [123 200 210]
  [124 201 211]
  ...
  [  2 131 160]
  [  3 132 163]
  [  2 131 162]]]


----------X------------X-----------------------X


120000
(200, 200, 3)
[[[230 170 170]
  [244 210 209]
  [242 218 216]
  ...
  [144   5   2]
  [158  10   8]
  [166   8   9]]

 [[217 118 113]
  [251 191 191]
  [240 215 210]
  ...
  [138   9   4]
  [149  11   8]
  [157   7   6]]

 

In [5]:
len(main_list)

5

In [6]:
main_list

[array([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        ...,
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=uint8), array([[[230, 170, 170],
         [244, 210, 209],
         [242, 218, 216],
         ...,
         [144,   5,   2],
         [158,  10,   8],
       

In [12]:
main_arr= np.array(main_list)
print("FINAL NUMPY ARRAY :\n\n ",main_arr)

FINAL NUMPY ARRAY :

  [[[[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]

  [[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]

  [[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]

  ...

  [[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]

  [[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]

  [[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]]


 [[[230 170 170]
   [244 210 209]
   [242 218 216]
   ...
   [144   5   2]
   [158  10   8]
   [166   8   9]]

  [[217 118 113]
   [251 191 191]
   [240 215 210]
   ...
   [138   9   4]
   [149  11   8]
   [157   7   6]]

  [[210 150 152]
   [209 133 135]
   [219 199 192]
   ...
   [120   1   0]
   [1

In [13]:
main_arr.shape

(5, 200, 200, 3)

In [14]:
main_arr.ndim

4

In [15]:
main_arr.size

600000